services:

    scout.form.flow.healthForm:
        class: ScoutEvent\ManagementBundle\Form\HealthFormFlow
        parent: craue.form.flow
        scope: request

    kernel.listener.logged_in_user_listener:
        class: ScoutEvent\ManagementBundle\Listener\LoggedInUserListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ @router, @service_container, @doctrine.orm.entity_manager ]  
